#!/usr/bin/env python3
"""Full C code generator for c_fsm engine.

Reads an FSM JSON export from c_fsm_ui and emits a complete C source file
with X-macro enums, name arrays, forward declarations, and the states[] table.

Usage:
    python3 gen_fsm_states.py [fsm.json] > fsm_states.c
"""

import json
import sys
from collections import defaultdict


def sanitize(name):
    """Convert a name to a valid C identifier."""
    return name.strip().replace(" ", "_")


def emit_xmacro(out, macro_name, entries):
    """Emit an X-macro #define block."""
    out.append(f"#define {macro_name}(X) \\")
    for i, entry in enumerate(entries):
        last = i == len(entries) - 1
        out.append(f"  X({entry})" + ("" if last else " \\"))


def generate(fsm_path):
    with open(fsm_path) as f:
        fsm = json.load(f)

    states = fsm["states"]
    transitions = fsm["transitions"]
    id_to_name = {s["id"]: sanitize(s["name"]) for s in states}

    # --- Determine state order: ST_NONE, initial state, rest in JSON order, ST_COUNT ---
    initial_name = None
    rest_names = []
    for s in states:
        name = id_to_name[s["id"]]
        if s.get("isInitial"):
            initial_name = name
        else:
            rest_names.append(name)
    all_state_names = ["ST_NONE"]
    if initial_name:
        all_state_names.append(initial_name)
    all_state_names.extend(rest_names)
    all_state_names.append("ST_COUNT")

    # --- Collect unique event triggers sorted alphabetically ---
    event_set = set()
    for t in transitions:
        trigger = sanitize(t["trigger"])
        if trigger:
            event_set.add(trigger)
    all_event_names = ["EVT_NONE"] + sorted(event_set)

    # --- Group transitions by source state, validate priorities ---
    by_from = defaultdict(list)
    for t in transitions:
        by_from[t["from"]].append(t)

    errors = []
    for sid, lst in by_from.items():
        priorities = [t.get("priority", 0) for t in lst]
        seen = set()
        for p in priorities:
            if p in seen:
                errors.append(
                    f"State '{id_to_name[sid]}' has multiple transitions with priority {p}"
                )
            seen.add(p)
    if errors:
        for e in errors:
            print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    for lst in by_from.values():
        lst.sort(key=lambda t: t.get("priority", 0))

    # --- Collect unique callback names grouped by signature ---
    action_fns = set()  # void(fsm_t*, void*, event_id, const void*)
    guard_fns = set()  # bool(const fsm_t*, const void*, event_id, const void*)

    for s in states:
        if s.get("onEnter"):
            action_fns.add(sanitize(s["onEnter"]))
        if s.get("onExit"):
            action_fns.add(sanitize(s["onExit"]))
    for t in transitions:
        if t.get("guard"):
            guard_fns.add(sanitize(t["guard"]))
        if t.get("action"):
            action_fns.add(sanitize(t["action"]))

    # --- Generate output ---
    out = []

    out.append(
        f"/* AUTO-GENERATED by gen_fsm_states.py from {fsm_path} -- do not edit */"
    )
    out.append('#include "fsm.h"')
    out.append("")

    # X-macros
    emit_xmacro(out, "MY_STATES", all_state_names)
    out.append("")
    emit_xmacro(out, "MY_EVENTS", all_event_names)
    out.append("")

    # Enums and name arrays
    out.append("#define GEN_ENUM(E) E,")
    out.append("#define GEN_STR(E) #E,")
    out.append("typedef enum { MY_STATES(GEN_ENUM) } state_id_t;")
    out.append("typedef enum { MY_EVENTS(GEN_ENUM) } event_id_t;")
    out.append("static const char* const state_names[] = { MY_STATES(GEN_STR) };")
    out.append("static const char* const event_names[] = { MY_EVENTS(GEN_STR) };")
    out.append("")

    # Forward declarations
    out.append("/* Forward declarations for user-supplied callbacks */")
    for fn in sorted(action_fns - guard_fns):
        out.append(f"extern void {fn}(fsm_t*, void*, event_id, const void*);")
    for fn in sorted(guard_fns):
        out.append(
            f"extern bool {fn}(const fsm_t*, const void*, event_id, const void*);"
        )
    for fn in sorted(guard_fns & action_fns):
        # Name appears as both guard and action — emit action signature
        out.append(f"extern void {fn}(fsm_t*, void*, event_id, const void*);")
    out.append("")

    # States array
    out.append("// fmt: off")
    out.append("static const state_t states[ST_COUNT] = {")

    for s in states:
        sid = s["id"]
        name = id_to_name[sid]
        out.append(f"  [{name}] = {{")

        if s.get("onEnter"):
            out.append(f"    .on_enter = {sanitize(s['onEnter'])},")
        if s.get("onExit"):
            out.append(f"    .on_exit = {sanitize(s['onExit'])},")
        if s.get("timeout_ms") is not None:
            out.append(f"    .timeout_ms = {s['timeout_ms']},")

        out.append("    .transitions = (const transition_t[]) {")

        for t in by_from.get(sid, []):
            trigger = sanitize(t["trigger"])
            guard = sanitize(t["guard"]) if t.get("guard") else None
            action = sanitize(t["action"]) if t.get("action") else None

            # Determine target: internal → ST_NONE; self-loop without
            # explicit internal field → ST_NONE (backward compat);
            # otherwise real target.
            internal = t.get("internal", False)
            if internal:
                target = "ST_NONE"
            elif t["from"] == t["to"] and "internal" not in t:
                target = "ST_NONE"
            else:
                target = id_to_name[t["to"]]

            parts = [f".event = {trigger}"]
            if guard:
                parts.append(f".guard = {guard}")
            if action:
                parts.append(f".action = {action}")
            parts.append(f".target = {target}")

            out.append(f"      {{ {', '.join(parts)} }},")

        out.append("      {0}, /* sentinel */")
        out.append("    }")
        out.append("  },")

    out.append("};")
    out.append("// fmt: on")

    if initial_name:
        out.append("")
        out.append(f"#define INITIAL_STATE {initial_name}")

    print("\n".join(out))


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "fsm.json"
    generate(path)
